language: generic

sudo: required

os:
  - linux
  - osx

env:
  matrix:
  - CONDA_PY=27
  - CONDA_PY=35
  - CONDA_PY=36

install:
- |
  echo "Installing a fresh version of Miniconda."
  MINICONDA_URL="https://repo.continuum.io/miniconda"
  MINICONDA_FILE="Miniconda3-latest-$(case $TRAVIS_OS_NAME in (linux) echo Linux;; (osx) echo MacOSX;;esac)-x86_64.sh"
  curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
  bash $MINICONDA_FILE -b
- |
  echo "Configuring conda."
  source $HOME/miniconda3/bin/activate root
  conda install -y conda-build anaconda-client

script:
- conda build -c intake/label/main ./conda

notifications:
  email: false
  on_success: change
  on_failure: always
